# Generated by Django 5.0.1 on 2024-01-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=100)),
                ("job_location", models.CharField(max_length=100)),
                ("job_salary", models.CharField(max_length=100)),
                ("job_description", models.TextField()),
                ("job_requirement", models.TextField()),
                ("job_benefit", models.TextField()),
                ("job_posted_date", models.DateField()),
                ("job_expired_date", models.DateField()),
                ("contact_name", models.CharField(max_length=100)),
                ("contact_phone", models.CharField(max_length=100)),
                ("contact_address", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "job",
            },
        ),
    ]
