# Generated by Django 5.0.1 on 2024-01-28 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0002_alter_job_job_expired_date_alter_job_job_posted_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="job_benefit",
        ),
    ]
