# Generated by Django 5.0.1 on 2024-01-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0003_remove_job_job_benefit"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="source_link",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
