# Generated by Django 5.0.1 on 2024-01-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0004_job_source_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company_name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="job",
            name="contact_address",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="job",
            name="contact_name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="job",
            name="contact_phone",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_location",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_salary",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_title",
            field=models.CharField(max_length=128),
        ),
    ]
