# Generated by Django 5.0.1 on 2024-01-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0006_alter_job_company_name_alter_job_contact_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company_name",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="contact_address",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="contact_name",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="contact_phone",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_expired_date",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_location",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_requirement",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_salary",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
