# Generated by Django 5.0.1 on 2024-01-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0007_alter_job_company_name_alter_job_contact_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="encode_content_hash",
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
    ]
